person(X)
hatRang(professor, giesl)
hatRang(assistent, rosarius)
hatRang(assistent, kassing)
hatRang(assistent, lommen)
hatRang(assistent, meyer)
hatRang(hiwi, kroebel)
hatRang(hiwi, wittenhorst)
hatRang(student, enial)
hatRang(student, mart)
hatRang(student, oll)
